'use strict';

const formats = {
  TD1: 'TD1',
  TD2: 'TD2',
  TD3: 'TD3',
  SWISS_DRIVING_LICENSE: 'SWISS_DRIVING_LICENSE',
  FRENCH_NATIONAL_ID: 'FRENCH_NATIONAL_ID',
  FRENCH_DRIVING_LICENSE: 'FRENCH_DRIVING_LICENSE',
  ESTONIAN_DRIVING_LICENSE: 'ESTONIAN_DRIVING_LICENSE',
  IRELAND_DRIVING_LICENSE: 'IRELAND_DRIVING_LICENSE',
  NETHERLANDS_DRIVING_LICENSE: 'NETHERLANDS_DRIVING_LICENSE',
  BOTSWANA_TD1: 'BOTSWANA_TD1',
  CROATIA_DRIVING_LICENSE: 'CROATIA_DRIVING_LICENSE',
  MOZAMBIQUE_TD1: 'MOZAMBIQUE_TD1',
  MEXICAN_ID_CARD: 'MEXICAN_ID_CARD'
};
Object.freeze(formats);

module.exports = formats;
